arb-dir: lib/l10n
output-dir: lib/l10n/generated
template-arb-file: app_en.arb
output-localization-file: app_localization.dart
output-class: AppLocalization
synthetic-package: false
nullable-getter: false
untranslated-messages-file: l10n_errors.txt